### ISSUE TITLE
The only Chrome revision guaranteed to work is chrome revision r722234

### ISSUE THREAD

**Issue by linibensonjr** [lawrensylvan/linkedin-learning-courses-downloader#1] opened 2020-05-18 20:31 UTC
It wouldn't sign me in, although the first trial seem successful, but it later return:
TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is chrome revision r722234.

**Comment by lawrensylvan** [comment] 2020-05-19 09:22
That error is raised by Puppeteer, a library that silently opens a Chrome (Chromium) navigator in the background and does all the clicks required to download the lessons.

The issue [has been reported several times](https://github.com/puppeteer/puppeteer/issues/1347) on Puppeteer's Github.
What I suggest : 
- Verify that you have in your package.json exactly the same puppeteer version than in the package-lock.json
- Try [this solution](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-windows)
- Try disabling your proxy
- Try to toggle "headless" to false (in downloader.js) to see the Chrome actually running

Good luck !
If you find something to add in the Puppeteer config that would make the whole codebase work under a wider range of configs, tell me what you did !

**Comment by linibensonjr** [comment] 2020-05-19 22:50
Thank you for the suggestions. I try them out and get back to you

**Comment by shadowdragon007** [comment] 2020-07-29 12:26
hi toggling the headless to false did work. but there is another problem for me, my access to LinkedIn is provided by my university and is required to use a single sign-on function.  before I can even input my details on single sign on-page the tab, get refreshed. 
can u please add a delay of 5 to 10 seconds to go from username page to password page then to my organization page, please

**Comment by lawrensylvan** [comment] 2020-08-23 20:10
Duplicate of [this issue](https://github.com/lawrensylvan/linkedin-learning-courses-downloader/issues/8)

**Closed by lawrensylvan** 2020-08-23 20:10 UTC
